name: Build

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: 📦 Install
      run: npm ci

    - name: 🧹 Lint
      run: npm run lint

    - name: ✅ Tests
      run: npm test

    - name: 🛠 Build
      run: npm run build:dev

    - name: 🗜 Deploy artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
   

  gh-pages:
    name: 📄 GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'

    - name: Delete old files
      run: |
        git config --local user.email "githubactions@yuste.com"
        git config --local user.name "GitHub Action"
        rm -rf *
        git add -u
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: dist

    - name: 🚀 Publish in gh-pages
      run: |
        git add .
        git commit -m "Update GitHub pages" || true
        git push
